### ISSUE TITLE
 Fatal error: Call to a member function make() on a non-object in C:\dev\workspace\fb100-beam-history\trunk\source_slim\vendor\illuminate\support\Illuminate\Support\helpers.php on line 493

### ISSUE THREAD

**Issue by flipace** [clickcoder/slim-blade#1]
When trying to use Blade as the template engine i get the following error:

Fatal error: Call to a member function make() on a non-object in C:\dev\workspace\fb100-beam-history\trunk\source_slim\vendor\illuminate\support\Illuminate\Support\helpers.php on line 493

Any ideas?

**Comment by clickcoder** [comment]
Should be fixed now

**Comment by flipace** [comment]
Awesome! Works great. Thank you!
