### ISSUE TITLE
make() error

### ISSUE THREAD

**Issue by ghost** [clickcoder/slim-blade#2]
When I call $app->render( 'template' ) I receive the following error.

Fatal error: Call to a member function make() on a non-object in /home/admin/vendor/illuminate/support/Illuminate/Support/helpers.php on line 493

**Comment by jamirhuamancampos** [comment]
Hello, you need to change

$app = new \Slim\Slim(array('view' => new \Slim\Views\Blade(),'templates.path' => '/templates'));

for this

$app = new \Slim\Slim(array('view' => new \Slim\Views\Blade(),'templates.path' => dirname(FILE) .'/templates'));

and in your file helpers.php line 493

if ( ! function_exists('base_path'))
{
/**
- Get the path to the base of the install.
  *
- @param string $path
- @return string
  */
  
  function base_path($path = '')
  {  
  //return app()->make('path.base').($path ? '/'.$path : $path);  
          return $path;
  }
  }

regards

**Comment by ghost** [comment]
Yeah that's what I ended up doing.

**Comment by jamirhuamancampos** [comment]
That's good
